export const API = {
  health: '/health',
  metrics: '/metrics',
  node: {
    status: '/v1/node/status',
    system: '/v1/node/system',
    version: '/v1/node/version',
    credits: '/v1/node/credits',
    creditsHistory: '/v1/node/credits/history',
    creditsTier: '/v1/node/credits/tier',
    connections: '/v1/node/connections',
    logs: '/v1/node/logs',
    logsStream: '/v1/node/logs/stream',
    activity: '/v1/node/activity',
    activityStream: '/v1/node/activity/stream',
    peers: '/v1/node/peers',
    config: '/v1/node/debug/config',
    federation: '/v1/node/federation',
    federationInvite: '/v1/node/federation/invite',
    federationJoin: '/v1/node/federation/join',
    federationLeave: '/v1/node/federation/leave',
    federationMemberships: '/v1/node/federation/memberships',
    publicDashboard: '/v1/node/public/dashboard',
    publicStats: '/v1/node/public/stats',
    fleetHardware: '/v1/node/fleet/hardware',
    relay: '/v1/node/relay',
    relayAdd: '/v1/node/relay/add',
    relayRemove: '/v1/node/relay/remove',
    relayRefresh: '/v1/node/relay/refresh',
    telemetry: '/v1/node/settings/telemetry',
    secrets: '/v1/node/settings/secrets',
  },
  models: {
    list: '/v1/models',
    local: '/v1/node/models',
    saved: '/v1/node/models/saved',
    load: '/v1/node/models/load',
    unload: '/v1/node/models/unload',
    update: '/v1/node/models/update',
    reload: '/v1/node/models/reload',
    scope: '/v1/node/models/scope',
    removeConfig: '/v1/node/models/remove-config',
    loadStatus: '/v1/node/models/load-status',
    config: (name: string) => `/v1/node/models/${encodeURIComponent(name)}/config`,
    search: '/v1/node/models/search',
    searchFiles: (repo: string) => `/v1/node/models/search/${repo}/files`,
    download: '/v1/node/models/download',
    downloads: '/v1/node/models/downloads',
    localFiles: '/v1/node/models/local',
    deleteFile: '/v1/node/models/delete-file',
    suggested: '/v1/node/models/suggested',
  },
  chat: {
    completions: '/v1/chat/completions',
  },
  admin: {
    nodes: '/v1/admin/nodes',
    approveNode: (peerId: string) => `/v1/admin/nodes/${peerId}/approve`,
    removeNode: (peerId: string) => `/v1/admin/nodes/${peerId}/remove`,
    fleetCommand: '/v1/admin/fleet/command',
    fleetPeers: '/v1/admin/fleet/peers',
  },
} as const
